### ISSUE TITLE
Basic Example?

### ISSUE THREAD

**Issue by logankaser** [HugoBDesigner/love.gradient#1]
It is difficult to understand how this is meant to be used, a simple example would help a lot.

**Comment by HugoBDesigner** [comment]
Okay, so suppose you want a rectangle with a gradient (from green on center to red on edges), and you want it radial (color fades away from the center). You want it to be on X:5 and Y:5. Your rectangle is 30x50 pixels, and you want the radial gradient to go from the center to the edges. You just do this:

love.gradient.draw(function() love.graphics.rectangle("fill", 5, 5, 30, 50) end, "radial", 15+5, 25+5, 30, 50, {255, 0, 0, 255}, {0, 255, 0, 255})

If you feel like it didn't help much, just let me know so I can prepare a very simple code example that you can run and try for yourself :)

**Comment by logankaser** [comment]
I get it now. I'm writing a spring based water simulator module and I need
water to gradient (I'm drawing each spring as a polygon) and I was
surprised to find that love did not support this nativity.

Thank you for the awesome module!

**Comment by logankaser** [comment]
Wow, it's been a long six years since I opened this issue. Back then I was in high school, now I'm a full time programmer working on self-driving. I eventually completed my water simulator, it was actually the first graphical programming project I ever completed.
I haven't worked with love2d for years now, but the confidence I built by working on little toy projects back then has changed the trajectory of my life. Releasing small libraries like this can be unrewarding, and often we don't see the effect it has, so I wanted you to know that this little positive interaction on GitHub 6 years ago made a difference.
I wish you the best in all your endeavours

**Comment by HugoBDesigner** [comment]
Hahah, that's awesome man! Yeah, it was a similar thing for me. When I published this library, I was fresh out of high school. My toy projects landed me a mobile app developer position in a startup, then a full-stack web developer for an accounting company. I've now decided to invest some time and effort into making my first full-scale Love2D game, and I took the opportunity to also update this library, since I came to need it. I'm very glad it had a positive impact on your life, and I'm sorry it took 6 years to finally put a readable example on the project, ha ha.
Best regards, and thanks for the kind words!
